### PR TITLE
Specifying software karan

### PR DESCRIPTION
**Pull request by karanahuja**
@nlacava could you add this please?

### CODE REVIEW

**Comment by aanchalsaxena** [comment]
@karanahuja you can also add "describing user personas"

**Comment by nlacava** [comment]
@karanahuja how about thinking about whether someone should do web only vs. app, etc.??

**Comment by Ertanongun** [comment]
Great content. You could add an image :-)

**Comment by karanahuja** [comment]
giphy

**Comment by gunner103** [comment]
Your link should maybe point to a top 10 list of software used for specific tasks

**Comment by adi-m** [comment]
Looks fine to me :+1:

**Comment by aanchalsaxena** [comment]
Looks good to me :+1:

**Comment by nlacava** [comment]
:+1:

**Pull request merged**
