### PR TITLE
Identifying customer requirements

### PR DESCRIPTION
**Pull request by aanchalsaxena**
@nlacava WHAT DO YOU THINK ABOUT THE FILE

### CODE REVIEW

**Comment by Ertanongun** [comment]
Good stuff. You may add an image if you want ;-)

**Comment by nlacava** [comment]
@aanchalsaxena looks great! How about something around epics vs. non-epics?

**Comment by Ertanongun** [comment]
@adi-m Please comment as well ;-)

**Comment by gunner103** [comment]
@aanchalsaxena you can also mention realistic vs unrealistic customer requirements, how software limitations or costs might not allow these requirements to be met

**Comment by adi-m** [comment]
@aanchalsaxena looks good, you might want to add an image.

**Comment by aanchalsaxena** [comment]
@nlacava, @Ertanongun , @gunner103, @karanahuja - Updated the document with some feedback. Not able to add the image right now. Can you give me a go ahead. Thanks!

**Comment by adi-m** [comment]
:+1:

**Comment by nlacava** [comment]
:+1:

**Pull request merged**
