### PR TITLE
Questions to ask when hiring

### PR DESCRIPTION
**Pull request by nlacava**
@aanchalsaxena what do you think of this?

### CODE REVIEW

**Comment by nlacava** [comment]
@peterbell how do i get the links to work??

**Comment by Ertanongun** [comment]
This is great Nicholas! Thanks Fahd

**Comment by nlacava** [comment]
@Ertanongun no tips to improve things?

**Comment by aanchalsaxena** [comment]
@nlacava you need to add the link and images

**Comment by karanahuja** [comment]
Sounds like a fun interview! You could also ask them for their GitHub account to know if they're for real

**Comment by gunner103** [comment]
@nlacava don't forget to ask for previous work, perhaps his GitHub account or links to published work.

**Comment by PeterBell** [comment]
Hey @nlacava for the links to show on the website, it'd have to be a "markdown" file which means it needs a file extension of .md. If you can figure out how to rename the file using GitHub (it can be done), feel free, but otherwise I wouldn't worry about it for this project.

**Comment by adi-m** [comment]
@nlacava I concur with requesting a GitHub account. Other than that very nice!

**Pull request merged**
