### PR TITLE
Key learnings on APIs is by fahd hajji

### PR DESCRIPTION
**Pull request by Ertanongun**
Team, please comment and share your knowledge.

### CODE REVIEW

**Comment by nlacava** [comment]
This looks pretty great, you should change the title from ap to api

**Comment by Ertanongun** [comment]
Thank will do!

**Comment by aanchalsaxena** [comment]
@Ertanongun looks good to me

**Comment by Ertanongun** [comment]
@gunner103 @aanchalsaxena @karanahuja Team, please comment as well :-)

**Comment by gunner103** [comment]
great info, Fahd! Maybe put your points in a list for better presentation?

**Comment by nlacava** [comment]
You need to add a profile picture @Ertanongun

**Comment by aanchalsaxena** [comment]
Looks good to me :+1:

**Comment by nlacava** [comment]
:+1:

**Comment by adi-m** [comment]
:+1:

**Comment by Ertanongun** [comment]
Thanks guys!

**Pull request merged**
