### PR TITLE
Update Benefits-of-Mobile-Apps-vs-Websites

### PR DESCRIPTION
**Pull request by gunner103**
Tried to summarize main points of the advantages of each

### CODE REVIEW

**Comment by nlacava** [comment]
@gunner103 Looks great! Apps are also only useful for the user if they are going to use it at least once a week

**Comment by aanchalsaxena** [comment]
@gunner103 this looks good to me. You may add an image also.

**Comment by gunner103** [comment]
@karanahuja any thoughts on this?

**Comment by Ertanongun** [comment]
Very well done. Thanks Fahd

**Comment by gunner103** [comment]
@karanahuja will do, thanks for the suggestion

**Comment by gunner103** [comment]
@karanahuja @nlacava @aanchalsaxena @adi-m @Ertanongun  changes made, can I get a :+1: to merge please?

**Comment by adi-m** [comment]
Looks good to me! :+1:

**Comment by aanchalsaxena** [comment]
Looks good to me :+1:

**Comment by nlacava** [comment]
:+1:

**Comment by gunner103** [comment]
@peterbell @chowdhury Can't seem to merge my pull request, any help would be appreciated :)

**Comment by PeterBell** [comment]
Hey @gunner103 looks like more than one branch changed the same file, so you're not going to be able to merge this. Add me as a collaborator to your repo (peterbell - using settings - collaborators) and I'll download this, resolve the merge conflict and merge it for you.

**Comment by gunner103** [comment]
@nlacava would you please add @PeterBell as a collaborator to our repo? Thanks!

**Comment by gunner103** [comment]
@PeterBell Done! Thanks again for your help

**Comment by PeterBell** [comment]
Downloaded it, fixed the conflict (someone had deleted the Benefits-of-Mobile-Apps-vs-Websites file on another branch) and merged the PR. You should be all good now!

**Pull request merged**
