### PR TITLE
what-happens-when-I-type-a-URL-Adi

### PR DESCRIPTION
**Pull request by adi-m**
Hey team, check out the file I created with my lesson and let me know what you think.

### CODE REVIEW

**Comment by adi-m** [comment]
Hey team, take a look at this file and let me know if you have any comments.
@gunner103 @aanchalsaxena @karanahuja @Ertanongun @nlacava

**Comment by aanchalsaxena** [comment]
@adi-m - You can also talk about different IP addresses.

**Comment by nlacava** [comment]
@adi-m I think this looks great, good job!

**Comment by adi-m** [comment]
@aanchalsaxena @nlacava @gunner103 Thanks for the comments - made a few changes. Give me thumbs up if this is OK. Thanks!

**Comment by gunner103** [comment]
:+1:

**Comment by nlacava** [comment]
:+1:

**Pull request merged**
